### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by IceSentry** [clubcapra/capra_web_ui#37]
- [x] Wrap the current ui with electron
- [ ] If possible keep the ui working on the web too.

**Comment by IceSentry** [comment]
The app now works in electron, the website support is currently on hold. Will investigate in a different issue in the future when necessary.

**Comment by LazyEngineerToBe** [comment]
Should we disable the GitHub page then?

**Comment by IceSentry** [comment]
Nope, I will add a small page that tells people to download the latest release with a link to github

**Comment by LazyEngineerToBe** [comment]
Sounds good!
