### ISSUE TITLE
EStop Button should be triggered by the spacebar

### ISSUE THREAD

**Issue by LazyEngineerToBe** [clubcapra/capra_web_ui#42]
Add a function to handle onKeyDown() events. If space (keyCode: 32) is pressed then the stopRobot() function should be called.

**Comment by Balnian** [comment]
So we want to remove the possibility to put spaces in any fields in the future? I understand that it's the "perfect" key (size wise) put I find this decision a bit restrictive for the future

**Comment by LazyEngineerToBe** [comment]
Nope, it will be disabled in the settings tab.

**Comment by Balnian** [comment]
Ok! Sounds goo

**Comment by Balnian** [comment]
Ok sounds good!
(Sorry for the close/open, fat fingers on mobile are to blame)

**Comment by IceSentry** [comment]
Could be disabled in any input field actually.
