### ISSUE TITLE
Improve input handling

### ISSUE THREAD

**Issue by IceSentry** [clubcapra/capra_web_ui#47]
create a new input system
- [x] allow keyboard and gamepad bindings for the same action
- [x] enable/disable specific actions when necessary // You can change the current actionMap or stop an input system
- [x] support spacemouse
- [x] give a context object when an action is performed that contains things like the gamepadState that triggered the action
~~- [ ] create a useInputAction() hook~~ // out of scope

**Comment by LazyEngineerToBe** [comment]
It would be nice to show something similar to this when the controller isn't connected.
![disconnected](https://gamepadviewer.com/xbox-assets/disconnected.svgz)
